#!/bin/sh
# Check if this is the initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1
then
		against=HEAD
else
		# Initial commit: diff against an empty tree object
		against=$(git hash-object -t tree /dev/null)
fi
pwd=$(pwd) && echo "Empacotando o diretorio: $pwd"
snbxnm=$(git config --global user.name)
tar -hcvzf upload.tar.gz --exclude=*node_modules* --exclude=*site-packages* --exclude=*.github* --exclude=*.git* --exclude=*upload.tar.gz* ./*
echo "baixando arquivos..."
wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.6.8.0/vosp-api-wrappers-java-21.6.8.0.jar
echo "Iniciando análise..."
hashcommit=$(git rev-parse --verify HEAD)
java -jar veracode-wrapper.jar -action UploadAndScan -appname "NodeGoat-Azure" -createprofile false -autoscan true -filepath upload.tar.gz -version "Scan commit $hashcommit with git Hooks" -scantimeout 15 -createsandbox true -sandboxname "$snbxnm Sandbox"
rm upload.tar.gz
rm veracode-wrapper.jar
